algoritmo "Questão 9"
// Função :  Potenciação e Radiciação
// Autor : Vitória Silva
// Data : 22/06/2021
// Seção de Declarações 
var
   x1, x2, y1, y2, d: real
inicio
// Seção de Comandos 
escreval("Ponto x1: ")
leia(x1)
escreval("Ponto x2: ")
leia(x2)
escreval("Ponto y1: ")
leia(y1)
escreval("ponto y2: ")
leia(y2)

d <- raizq(((x2 - x1) ^ 2) + ((y2 - y1) ^ 2)))
escreval("A distancia é igual a ", d:4:2)
fimalgoritmo
