algoritmo "Questão 12"
// Função : Raiz Quadrada
// Autor :  Vitória Silva
// Data : 22/06/2021
// Seção de Declarações 
var
   num, raiz: real
inicio
// Seção de Comandos 
raiz <- 0
escreval("digite um número: ")
leia(num)
enquanto (num>0) faca
         raiz<-raizq(num)
         escreval("A raiz quadrada de ", num, " é ", raiz)
         escreval("Digite outro numero ou -1 para sair: ")
         leia(num)
fimenquanto
fimalgoritmo
